# Generated by Django 4.1 on 2022-08-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-created_at',)},
        ),
    ]
